# Generated by Django 3.2.5 on 2021-12-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20211214_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=1000)),
                ('image_profile', models.ImageField(blank=True, upload_to='students/vacancy_file/')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
